sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6
  - "stable"

before_install:
  - "npm config set progress=false"

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
